<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		PENILAIAN KANTOR CABANG
	</div>

<div class="panel-body" id="profile">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('profile/save')?>">
				<div class="form-group">
					<label>Kantor Cabang</label>
					<select name="office_id" id="office_id" class="form-control" >
						<option value=""><?php echo lang('Pilih Cabang')?></option>
						<?php foreach($offices as $key => $office):?>
						<option value="<?php echo $office['id'];?>"><?php echo $office['name'];?></option>

						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
				<label>Bulan</label>
					<select name="month" id="bulan" class="form-control" >
						<option value="januari">Januari</option>
						<option value="februari">Februari</option>
						<option value="maret">Maret</option>
						<option value="april">April</option>
						<option value="mei">Mei</option>
						<option value="juni">Juni</option>
						<option value="juli">Juli</option>
						<option value="agustus">Agustus</option>
						<option value="september">September</option>
						<option value="oktober">Oktober</option>
						<option value="nopember">Nopember</option>
						<option value="desember">Desember</option>
					</select>
				</div>
				<div class="form-group">
				<label>Tahun</label>
					<select name="year" id="year" class="form-control" >
						<?php for($ii=2000;$ii<=date("Y");$ii++):?>
							<option <?php if($ii == date('Y')): echo 'selected'; endif;?> value="<?php echo $ii;?>"><?php echo $ii;?></option>
						<?php endfor;?>
					</select>
				</div>
				<a class="btn btn-loading btn-primary">Load</a>
				
				<?php /*** <div class="form-group">
				<label>Kriteria</label>
					<select name="criteria_id" id="criteria_id" class="form-control" >
						<option value=""><?php echo lang('Pilih Kriteria')?></option>
						<?php foreach($criterias as $key => $criteria):?>
						<option value="<?php echo $criteria['id'];?>"><?php echo $criteria['criteria'];?></option>

						<?php endforeach;?>
					</select>
				</div>***/?>
				<div class="form-group">
					<div class="subcriteria-ajax"></div>
				</div>
				
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>