
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>Nama Kantor Cabang</th>
											<th>Bulan</th>
                                            <th>Tahun</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                       <?php $i = 1; foreach($profiles as $profile):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo OfficeModel::getName($profile['office_id'])?></td>
                                            <td><?php echo $profile['month']?></td>
                                            <td><?php echo $profile['year']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('profile/detail/'.$profile['id'])?>">
													<i class="fa fa-pencil-square fa-lup"></i>
												</a>
												<a href="<?php echo site('profile/delete/'.$profile['id'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr> 
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('profile/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->