
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
											<th>Tgl Pinjam</th>
                                            <th>Nama Anggota</th>
                                            <th>Resort</th>
											
											<th>Lama cicilan</th>
											<th>Pokok</th>
											<th>Bunga</th>
											<th>Total</th>
											<th>Ket.</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($pinjaman as $_pinjaman):?>
										<tr class="">
											<td><?php echo $i++;?></td>
											<td><?php echo $_pinjaman['tgl_mulai'];?></td>	
                                            <td><?php echo $anggotaModel->getNama($_pinjaman['id_anggota']); ?></td>
											<td><?php echo $resortModel->getKode($_pinjaman['id_resort']);?></td>												
                                           	<td><?php echo $_pinjaman['lama'];?></td>
											<td><?php echo $_pinjaman['pokok'];?></td>	
											<td><?php echo $_pinjaman['bunga'];?></td>
											<td><?php echo $_pinjaman['total'];?></td>
											<td><?php echo $_pinjaman['keterangan'];?></td>												
											<td class="center" align="center">
												<a href="<?php echo site('pinjaman/edit/'.$_pinjaman['id_pinjaman'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('pinjaman/delete/'.$_pinjaman['id_pinjaman'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>											
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('pinjaman/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->