<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Perubahan Data Resort<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('resort/update/'.$request['id_resort'])?>">				
				<div class="form-group">
					<label>Kode</label>
					<input class="form-control" name="kode" value="<?php echo (isset($request['kode']))? $request['kode']:'' ?>">					
				</div>
				<div class="form-group">
					<label>Pemegang Resort</label>
					<select class="form-control chosen-dropdown" data-allows-new-values="true" name="id_pegawai">
						<?php foreach($pegawai as $_pegawai):?>
						<?php $selected = '';?>
						<?php if($_pegawai['id_pegawai'] == $request['id_pegawai']) $selected='selected = "selected"';?>
						<option <?php echo $selected; ?> value="<?php echo $_pegawai['id_pegawai'];?>"><?php echo $_pegawai['nama'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label>Ketua</label>
					<select class="form-control chosen-dropdown" data-allows-new-values="true" name="ketua">
						<?php foreach($kpl as $_kpl):?>
						<?php $selected = '';?>
						<?php if($_kpl['id_pegawai'] == $request['ketua']) $selected='selected = "selected"';?>
						<option <?php echo $selected; ?> value="<?php echo $_kpl['id_pegawai'];?>"><?php echo $_kpl['nama'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				
				<button class="btn btn-primary" type="submit">Update</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>