
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>Kode Resort</th>
                                            <th>Kepala Resort</th>
											<th>Sales</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($resorts as $resort):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $resort['kode']?></td>
                                            <td><?php echo $resortModel->getNama($resort['ketua']);?></td>
                                            <td><?php echo $resortModel->getNama($resort['id_pegawai']);?></td>											
                                            <td class="center" align="center">
												<a href="<?php echo site('resort/edit/'.$resort['id_resort'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('resort/delete/'.$resort['id_resort'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('resort/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->