<link rel="stylesheet" href="<?php echo BASE_URL; ?>Layout/libs/datepicker/css/datepicker.css" type="text/css" />
<link rel="stylesheet" href="<?php echo BASE_URL; ?>Layout/libs/event/calendar.css" type="text/css" />
<script src="<?php echo BASE_URL; ?>Layout/libs/datepicker/js/bootstrap-datepicker.js"></script>

<?php /** <div class="form-group">
  <label>Tanggal Bayar</label>
  <div id="dp3" class="input-append date" data-date-format="yyyy-mm-dd">
  <input name="tgl_masuk" class="span2" type="text" readonly="" value="<?php echo date('Y-m-d'); ?>" size="16">
  <span class="add-on">
  <i class="fa fa-calendar"></i>
  </span>
  </div>
  </div>
  <div class="form-group">
  <label>Jumlah Uang</label>
  <input  class="form-control" id="saldo" name="saldo" value="<?php echo (isset($request['saldo'])) ? $request['saldo'] : '' ?>">
  </div> ** */ ?>
<script>
    $(document).ready(function() {
        $('.input-append.date').datepicker({});
    });
</script>
<?php //pre($dataPeminjam)?>
<?php foreach ($dataPeminjam as $dataPinjam): ?>
<div class="clear"></div>
    <div class="col-lg-12" style="padding:0">
		<div class="col-lg-6" style="padding:0">
		<p><strong>Tanggal Pinjam</strong>   <?php echo $dataPinjam['tanggal']; ?> <br>
		<strong>Pinjaman pokok</strong>   <?php echo $dataPinjam['pokok']; ?>  <br>
		<strong>Jangka Pinjaman</strong>   <?php echo $dataPinjam['lama']; ?>  <br>
		<strong>Bunga</strong>  <?php echo $dataPinjam['bunga']; ?>  <br>
		<strong>Total Pinjaman</strong>   <?php echo $dataPinjam['total']; ?>  <br></p>
		</div>
		<div class="col-lg-6" style="padding:0">
		<p><strong>Nama Anggota</strong> <?php echo $dataPinjam['nama_anggota']; ?> <br>		
		<strong>Status</strong> <?php echo $dataPinjam['status']; ?>  <br>
		<strong>Resort</strong> <?php echo $dataPinjam['kode']; ?> </p>	
		</div>
	</div>			
	 <div id="event-kredit" class="col-lg-12" style=" background: none repeat scroll 0 0 #a1ddff;
    height: auto;
    margin-bottom: 20px;
    overflow: hidden;
    padding: 10px;">

	<li id="thismonth" style="list-style:none">
		<ol>
		<?php for($xx=1;$xx <= $dataPinjam['lama'];$xx++):?>
			<li data-event="<?php echo $xx;?>" class="payMe"><?php echo $xx; ?>
			<input style="display:none;" type="checkbox" name="event[]" class="data-event-index-<?php echo $xx;?>" data-index="<?php echo $xx;?>" value="<?php echo $xx;?>"/>
			</li>
		<?php endfor;?>	
		</ol>
	</li>
	
	
	</div>
<?php endforeach; ?>
<div class="clear"></div>
 <button class="btn btn-primary" type="submit">Simpan</button>
 <button class="btn btn-default" type="reset">Reset</button>
<script>
$(document).ready(function() {
	$('.payMe').click(function(){
		var event = $(this).attr('data-event');
		// console.log(event);
		if ($('input.data-event-index-'+event).is(':checked')) {
            $('input.data-event-index-'+event).prop('checked', false);
        }
        else {
            $('input.data-event-index-'+event).prop('checked', true);
        }
		
		if($(this).hasClass( "paid" )){
			$(this).removeClass('paid');
		} else {
			$(this).addClass('paid');
		}
		
	});
});

</script>

    <?php /**
      Array
      (
      [0] => Array
      (
      [id_anggota] => 100003
      [id_resort] => 5
      [pokok] => 2100000
      [bunga] => 20
      [tgl_mulai] => 2014-11-13
      [tgl_lunas] => 0000-00-00
      [keterangan] => dfdgdg
      [lama] => 30
      [total] => 2520000
      [tanggal] => 2014-11-13
      [kode_anggota] =>
      [nama_anggota] => aaa
      [kode] => Flava
      [ketua] => 1
      [id_pegawai] => 3
      [nama] => Jhony
      [id_pinjaman] => 16
      )

      )

     * * */ ?>
