<div class="col-lg-12">
    <?php echo (isset($msg)) ? $msg : ''; ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Form Tambah Simpanan Anggota<br/>
        </div>
        <div class="panel-body">

            <!-- /.row -->
                <div class="col-lg-12">
                    <form role="form" method="post" action="<?php echo site('angsuran/save') ?>">
                        <div class="form-group">
                            <label>No. Pinjaman</label><br/>
                            <select name="id_pinjaman" class="form-control chosen-dropdown" id="load_pinjaman" data-placeholder="Masukkan No. Pinjaman">
                                <option value="0"></option>
                                <?php foreach ($pinjaman as $pinjam): ?>					
                                    <option value="<?php print $pinjam['id_pinjaman']; ?>"><?php echo $pinjam['id_pinjaman'] . ' - ' . $pinjam['nama_anggota']; ?></option>						
                                <?php endforeach; ?>
                            </select>
                            <div class="loading" style="display:none;">Loading....</div>
                        </div>
                        <div class="response"></div>
                        <div class="newresponse"></div>

                       
                    </form>


                </div>	
           <?php /***  <div class="col-lg-12">
                <h3>Histori Angsuran</h3>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Tgl_bayar</th>											
                                <th>Bayar</th>
                                <th>Denda</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i = 1; ?>
                            <tr class="">
                                <td><?php echo $i++; ?></td>
                                <td><?php echo $i++; ?></td>
                                <td><?php echo $i++; ?></td>
                                <td><?php echo $i++; ?></td>
                                <td><?php echo $i++; ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            <!-- /.row -->
            </div> ***/?>
        </div>
    </div>

</div>


