
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <?php echo (isset($msg)) ? $msg : ''; ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $title; ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Tgl_bayar</th>
                                <th>Kode Pinjaman</th>
                                <th>Resort</th>	
                                <th>Nama Anggota</th>											
                                <th>Bayar</th>
                                <th>Denda</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php $i = 1;
                            foreach ($angsuran as $_angsuran): ?>
                                <tr class="">
                                    <td><?php echo $i++; ?></td>
                                    <td><?php echo $_angsuran['tgl_bayar']; ?></td>	
                                    <td><?php echo $_angsuran['id_pinjaman']; ?></td>
                                    <td><?php echo $_angsuran['kode']; ?></td>												
                                    <td><?php echo $_angsuran['nama_anggota']; ?></td>
                                    <td><?php echo $_angsuran['bayar']; ?></td>		
                                    <td><?php echo $_angsuran['denda']; ?></td>		
                                    <td><?php echo $_angsuran['status']; ?></td>													
                                    <?php /** <!--<td class="center" align="center">
                                      <a href="<?php echo site('simpanan/edit/'.$_angsuran['id_angsuran'])?>">
                                      <i class="fa fa-pencil-square fa-fw"></i>
                                      </a>
                                      <a href="<?php echo site('simpanan/delete/'.$_angsuran['id_angsuran'])?>">
                                      <i class="fa fa-times-circle fa-fw"></i>
                                      </a>
                                      </td>	-->		 * */ ?>								
<?php endforeach; ?>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>

            <div class="panel-body">
                <p>
                    <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('angsuran/addnew') ?>"><?php echo lang('Add New'); ?></a>

                </p>
            </div>


            <!-- /.panel-body -->



        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->