<div class="col-lg-12">
    <?php echo (isset($msg)) ? $msg : ''; ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Form Tambah Anggota<br/>
        </div>

        <div class="panel-body">

            <!-- /.row -->
            <div class="row">
                <div class="col-lg-6">
                    <form role="form" method="post" action="<?php echo site('anggota/save') ?>">
                        <div class="form-group">
                            <label>Nama Anggota</label>
                            <textarea cols="70" rows="2" name="nama_anggota"><?php echo (isset($request['nama_anggota'])) ? $request['nama_anggota'] : '' ?></textarea>
                        </div>
                        <div class="form-group">
                            <label>Telephone</label>
                            <input class="form-control" name="no_tlp" value="<?php echo (isset($request['no_tlp'])) ? $request['no_tlp'] : '' ?>">		
                        </div>
                        <div class="form-group">
                            <label>Alamat</label>
                            <textarea cols="70" rows="4" name="alamat"><?php echo (isset($request['alamat'])) ? $request['alamat'] : '' ?></textarea>
                        </div>
                        <button class="btn btn-primary" type="submit">Simpan</button>
                        <button class="btn btn-default" type="reset">Reset</button>
                    </form>
                </div>			
            </div>
            <!-- /.row -->
        </div>
    </div>

</div>
