
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>Nama Anggota</th>
                                            <th>No.tlp</th>
											<th>Alamat</th>
											<th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($anggota as $_anggota):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $_anggota['nama_anggota']; ?></td>
											<td><?php echo $_anggota['no_tlp'];?></td>												
                                            <td><?php echo $_anggota['alamat'];?></td>					
											<td><?php echo ($_anggota['status'])?'Aktif':'Tdk aktif';?></td>	
											<td class="center" align="center">
												<a href="<?php echo site('anggota/edit/'.$_anggota['id_anggota'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('anggota/delete/'.$_anggota['id_anggota'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>											
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('anggota/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->