<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo $title ?></title>

        <!-- Bootstrap Core CSS -->
        <link href="<?php echo $base_url; ?>css/bootstrap.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="<?php echo $base_url; ?>css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="<?php echo $base_url; ?>css/plugins/timeline.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="<?php echo $base_url; ?>css/sb-admin-2.css" rel="stylesheet">

        <!-- DataTables CSS -->
        <link href="<?php echo $base_url; ?>css/plugins/dataTables.bootstrap.css" rel="stylesheet">

        <link rel="stylesheet" href="<?php echo $base_url; ?>libs/chosen/chzn.css" type="text/css" />
        <!-- Morris Charts CSS -->
        <link href="<?php echo $base_url; ?>css/plugins/morris.css" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $base_url; ?>libs/datepicker/css/datepicker.css" type="text/css" />
        <!-- Custom Fonts -->
        <link href="<?php echo $base_url; ?>font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $base_url; ?>css/plugins/chart/css/graph.css" rel="stylesheet">
        <link href="<?php echo $base_url; ?>css/slide.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->



    </head>

    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php /*                     * <a class="navbar-brand" href="#">
                      <span><i class="fa fa-phone-square"></i></span>
                      MANAGEMENT KOPERASI </a> ** */ ?>
                    <ul class="nav navbar-nav">
                        <?php /** <li class="sidebar-search">
                          <img src="<?php echo site('Layout/images/koperasi.jpg');?>"/>
                          </li>** */ ?>
                        <?php $parameter = Core::request(); ?>
                        <li>
                            <a class="active" href="<?php echo site('/') ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li class="<?php echo ($parameter['controller'] == 'resort' || $parameter['controller'] == 'pegawai' || $parameter['controller'] == 'pengeluaran') ? 'active' : ''; ?>">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"><i class="fa fa-file fa-fw"></i> Management Kantor<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a  href="<?php echo site('pegawai/index') ?>"><i class="fa fa-file fa-fw"></i> Data Pegawai</a></li>
                                <li><a class="<?php echo ($parameter['controller'] == 'resort') ? 'active' : ''; ?>" href="<?php echo site('resort/index') ?>"><i class="fa fa-file fa-fw"></i> Data Resort</a></li>
                                <li><a class="<?php echo ($parameter['controller'] == 'target') ? 'active' : ''; ?>" href="<?php echo site('target/index') ?>"><i class="fa fa-file fa-fw"></i> Data Target Bulanan</a></li>
                                <li><a  href="<?php echo site('transaksi/index') ?>"><i class="fa fa-file fa-fw"></i> Data Transaksi Tambahan</a></li>
                            </ul>
                        </li>
                        <li class="<?php echo ($parameter['controller'] == 'angsuran' || $parameter['controller'] == 'simpanan' || $parameter['controller'] == 'anggota' || $parameter['controller'] == 'pinjaman') ? 'active' : ''; ?>">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"><i class="fa fa-file fa-fw"></i> Simpan - Pinjam<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="<?php echo ($parameter['controller'] == 'anggota') ? 'active' : ''; ?>" href="<?php echo site('anggota/index') ?>"><i class="fa fa-list  fa-fw"></i>Data Anggota</a></li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'pinjaman') ? 'active' : ''; ?>" href="<?php echo site('pinjaman/index') ?>"><i class="fa fa-outdent fa-fw"></i>Data Pinjaman</a>
                                </li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'simpanan') ? 'active' : ''; ?>" href="<?php echo site('simpanan/index') ?>"><i class="fa fa-outdent fa-fw"></i>Data Simpanan</a>
                                </li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'angsuran') ? 'active' : ''; ?>" href="<?php echo site('angsuran/index') ?>"><i class="fa fa-outdent fa-fw"></i>Data Angsuran Pinjaman</a>
                                </li>
                            </ul>
                        </li>
                        <li class="<?php echo ($parameter['controller'] == 'laporan') ? 'active' : ''; ?>">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"><i class="fa fa-file fa-fw"></i>Laporan<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a class="<?php echo ($parameter['controller'] == 'anggota') ? 'active' : ''; ?>" href="<?php echo site('laporan/anggota') ?>"><i class="fa fa-list  fa-fw"></i>Laporan Anggota</a></li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'pinjaman') ? 'active' : ''; ?>" href="<?php echo site('laporan/pinjaman') ?>"><i class="fa fa-outdent fa-fw"></i>Laporan Pinjaman</a>
                                </li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'simpanan') ? 'active' : ''; ?>" href="<?php echo site('laporan/simpanan') ?>"><i class="fa fa-outdent fa-fw"></i>Laporan Simpanan</a>
                                </li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'angsuran') ? 'active' : ''; ?>" href="<?php echo site('laporan/angsuran') ?>"><i class="fa fa-outdent fa-fw"></i>Laporan Angsuran</a>
                                </li>
                                <li>
                                    <a class="<?php echo ($parameter['controller'] == 'angsuran') ? 'active' : ''; ?>" href="<?php echo site('laporan/angsuran') ?>"><i class="fa fa-outdent fa-fw"></i>Laporan Keuangan</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="<?php echo ($parameter['controller'] == 'user') ? 'active' : ''; ?>" href="<?php echo site('user') ?>"><i class="fa fa-user fa-fw"></i>Pengguna</a>
                        </li>
                        <li>
                            <a class="<?php echo ($parameter['controller'] == 'help') ? 'active' : ''; ?>" href="<?php echo site('help') ?>"><i class="fa fa-support fa-fw"></i>Bantuan</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <!--<li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>-->
                            <li><a href="<?php echo site('user/logout'); ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <img src="<?php echo site('Layout/images/koperasi.jpg'); ?>"/>
                            </li>
                            <li class="<?php echo ($parameter['controller'] == 'resort' || $parameter['controller'] == 'pegawai' || $parameter['controller'] == 'pengeluaran') ? 'active' : ''; ?>">
                                <a class=""><i class="fa fa-file fa-fw"></i> Management Kantor<span class="caret"></span></a>
                                <ul class="nav nav-second-level">
                                    <li><a  href="<?php echo site('pegawai/index') ?>"><i class="fa fa-file fa-fw"></i> Data Pegawai</a></li>
                                    <li><a class="<?php echo ($parameter['controller'] == 'resort') ? 'active' : ''; ?>" href="<?php echo site('resort/index') ?>"><i class="fa fa-file fa-fw"></i> Data Resort</a></li>
                                    <li><a  href="<?php echo site('transaksi/index') ?>"><i class="fa fa-file fa-fw"></i> Data Transaksi Tambahan</a></li>
                                </ul>
                            </li>
                            <li class="<?php echo ($parameter['controller'] == 'angsuran' || $parameter['controller'] == 'simpanan' || $parameter['controller'] == 'anggota' || $parameter['controller'] == 'pinjaman') ? 'active' : ''; ?>">
                                <a class="" ><i class="fa fa-file fa-fw"></i> Simpan - Pinjam<span class="caret"></span></a>
                                <ul class="nav nav-second-level">
                                    <li><a class="<?php echo ($parameter['controller'] == 'anggota') ? 'active' : ''; ?>" href="<?php echo site('anggota/index') ?>"><i class="fa fa-list  fa-fw"></i>Anggota</a></li>
                                    <li>
                                        <a class="<?php echo ($parameter['controller'] == 'pinjaman') ? 'active' : ''; ?>" href="<?php echo site('pinjaman/index') ?>"><i class="fa fa-outdent fa-fw"></i>Pinjaman</a>
                                    </li>
                                    <li>
                                        <a class="<?php echo ($parameter['controller'] == 'simpanan') ? 'active' : ''; ?>" href="<?php echo site('simpanan/index') ?>"><i class="fa fa-outdent fa-fw"></i>Simpanan</a>
                                    </li>
                                    <li>
                                        <a class="<?php echo ($parameter['controller'] == 'angsuran') ? 'active' : ''; ?>" href="<?php echo site('angsuran/index') ?>"><i class="fa fa-outdent fa-fw"></i>Angsuran</a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a class="<?php echo ($parameter['controller'] == 'user') ? 'active' : ''; ?>" href="<?php echo site('user') ?>"><i class="fa fa-user fa-fw"></i>Pengguna</a>
                            </li>

                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <?php /*             * <div class="row2">
              <div id="bg-header">

              </div>
              </div> * */ ?>

            <div id="page-wrapper">
                <div class="row2">
                    <div class="col-lg-12">
                        <h1 class="page-header"><?php echo $header; ?></h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>

                <?php echo $content; ?>
                <!-- /.row -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery Version 1.11.0 -->
        <script src="<?php echo $base_url; ?>js/jquery-1.11.0.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="<?php echo $base_url; ?>js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="<?php echo $base_url; ?>js/plugins/metisMenu/metisMenu.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="<?php echo $base_url; ?>js/plugins/morris/raphael.min.js"></script>
        <script src="<?php echo $base_url; ?>js/plugins/morris/morris.min.js"></script>
       <!-- <script src="<?php echo $base_url; ?>js/plugins/morris/morris-data.js"></script>-->

        <!-- DataTables JavaScript -->
        <script src="<?php echo $base_url; ?>libs/chosen/chosen.jquery.js"></script>
        <script src="<?php echo $base_url; ?>js/plugins/dataTables/jquery.dataTables.js"></script>
        <script src="<?php echo $base_url; ?>js/plugins/dataTables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $base_url; ?>libs/chosen/chzn.jquery.js"></script>
        <script src="<?php echo $base_url; ?>libs/datepicker/js/bootstrap-datepicker.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="<?php echo $base_url; ?>js/sb-admin-2.js"></script>
        <script>
            $(document).ready(function() {
                $('#dataTables-example').dataTable();
                $(".chosen-dropdown").chosen({no_results_text: 'Data tidak ditemukan!'});
                $(".chzn-select-deselect").chosen({allow_single_deselect: true, no_results_text: 'Data tidak ditemukan'});
                $(".chosen-select-no-results").chosen({
                    no_results_text: 'Data tidak ditemukan!'
                });
                $('.input-append.date').datepicker({
                });

            });
        </script>

        <script>
            var SITE_URL = "<?php echo $site_url; ?>"
        </script>

        <script type="text/javascript" src="<?php echo $base_url; ?>js/ajax.js"></script>

        <footer>
            <p>&copy;Copyright.STMIK Denpasar - 2014</p>
        </footer>

    </body>

</html>
