<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Tambah Simpanan Anggota<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('simpanan/save')?>">
				<div class="form-group">
					<label>Resort</label>
					<select name="id_resort" class="form-control chosen-dropdown" id="resort_load" data-placeholder="Pilih resort">
						<option value="0"></option>
						<?php foreach($resorts as $text):?>					
						<option value="<?php print $text['id_resort'];?>"><?php echo $text['kode'];?></option>						
						<?php endforeach;?>
					</select>
					<div class="loading" style="display:none;">Loading....</div>
				</div>
				<div class="response"></div>
				<div class="form-group">
					<label>Jenis Simpanan</label><br>
					<input type="radio" class="form-radio" id="jenis" name="jenis" checked value="DEBET">	DEBET
					<input type="radio" class="form-radio" id="jenis" name="jenis" value="KREDIT">	KREDIT					
				</div>
				<div class="form-group">
					<label>Jumlah Uang</label>
					<input  class="form-control" id="saldo" name="saldo" value="<?php echo (isset($request['saldo']))? $request['saldo']:'' ?>">		
				</div>
				
				<button class="btn btn-primary" type="submit">Simpan</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>

