
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
											<th>Tgl Simpan</th>
                                            <th>Nama Anggota</th>
                                            <th>Resort</th>											
											<th>Jenis</th>
											<th>Jumlah</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($simpanan as $_simpanan):?>
										<tr class="">
											<td><?php echo $i++;?></td>
											<td><?php echo $_simpanan['tgl_simpan'];?></td>	
                                            <td><?php echo $_simpanan['nama_anggota']; ?></td>
											<td><?php echo $_simpanan['kode'];?></td>												
                                           	<td><?php echo $_simpanan['jenis'];?></td>
											<td><?php echo $_simpanan['saldo'];?></td>											
											<?php /** <!--<td class="center" align="center">
												<a href="<?php echo site('simpanan/edit/'.$_simpanan['id_simpanan'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('simpanan/delete/'.$_simpanan['id_simpanan'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>	-->		 **/?>								
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('simpanan/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->