<!-- /.row -->
<div class="row">
<div class="col-lg-12">
	<div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>TENTANG TULISAN !!!</h4>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
		<h5>ABSTRAK</h5>
		<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        
	</div>
	</div>
</div>
	<div class="col-lg-4">
		

	
	<div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>SELAMAT DATANG !!!</h4>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">

		<div id="slider-shadow">
	<div id="slider">
		<div id="mask">
			<ul>
				
				<li>
					<img style="height:325px" src="<?php echo site('Layout/images/novi.jpg');?>"/>	
		
				</li>
				<li>
					<img style="height:325px" src="<?php echo site('Layout/images/novi2.jpg');?>"/>	
		
				</li>
				<li>
					<img style="height:325px" src="<?php echo site('Layout/images/novi3.jpg');?>"/>	
		
				</li>
				
			</ul>
		</div>
		<div id="progress">
		</div>
		<div id="overlay">
		</div>
		<div id="pause">
		</div>
	</div>
</div>
	</div></div>

</div>
	<div class="col-lg-8">
	<div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>TENTANG PENULIS !!!</h4>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
		<p>Nama : Novi</p>
		<p>Jurusan : Teknik Informatika</p>
		<p>Alamat : Denpasar</p>
	</div>
	</div>
</div>

</div>

	
<!-- /.row -->
			
