<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Kriteria<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('subcriteria/save')?>">
				<div class="form-group">
					<label>Kriteria</label>
					<select name="parent_id" class="form-control" >
						<?php foreach($parents as $key => $parent):?>
						<option value="<?php echo $parent['id'];?>"><?php echo $parent['criteria'];?></option>

						<?php endforeach;?>
					</select>
				</div>
				
				<div class="form-group">
					<label>Kode</label>
					<input class="form-control" name="kode" value="<?php echo (isset($request['kode']))? $request['kode']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Sub Kriteria</label>
					<input class="form-control" name="sub_criteria" value="<?php echo (isset($request['sub_criteria']))? $request['sub_criteria']:'' ?>">
				</div>
				 <div class="form-group">
					<label>Nilai Persentase Absolute</label>
					<input class="form-control" name="persentase" value="<?php echo (isset($request['persentase']))? $request['persentase']:'' ?>">
				</div> 
				<div class="form-group">
					<label>Faktor</label>
					<select name="factor" class="form-control" >
						<option value="ncf" <?php echo (isset($request['factor']) && $request['factor'] == 'ncf')? 'selected':'' ?>>Core Factor</option>
						<option value="ncf" <?php echo (isset($request['factor']) && $request['factor'] == 'nsf')? 'selected':'' ?>>Secondary Factor</option>
					</select>
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>