<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
											<th>Criteria</th>
                                            <th>Sub Criteria</th>
											<th>Kode</th>
											<?php /** <th>Persentase</th>
											<th>Nilai</th> ***/ ?>
                                            <th>Faktor</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($subcriterias as $criteria):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo SubcriteriaModel::getCriteriabyId($criteria['parent_id'])?></td>
                                            <td><?php echo $criteria['sub_criteria']?></td>
                                            <td><?php echo $criteria['kode']?></td>
											<?php /** <td><?php echo $criteria['persentase']?></td>
											<td><?php echo $criteria['value']?></td> **/ ?>
											<td><?php echo $criteria['factor']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('subcriteria/edit/'.$criteria['id'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('subcriteria/delete/'.$criteria['id'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('subcriteria/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->