<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Perubahan Data Pegawai<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('pegawai/update/'.$request['id_pegawai'])?>">				
				<div class="form-group">
					<label>Nama Lengkap</label>
					<input class="form-control"  name="nama" value="<?php echo (isset($request['nama']))? $request['nama']:'' ?>">					
				</div>
				<div class="form-group">
					<label>Posisi</label>
					<select class="form-control chosen-dropdown" data-allows-new-values="true" name="posisi">
						
						<option value="kpl" <?php echo ($request['posisi']=='kpl')? 'selected="selected"': ''?>>Kepala Resort</option>
						<option value="res" <?php echo ($request['posisi']=='res')? 'selected="selected"': ''?>>Pemegang Resort</option>
						<option value="ksr" <?php echo ($request['posisi']=='ksr')? 'selected="selected"': ''?>>Kasir</option>
						<option value="pks" <?php echo ($request['posisi']=='pks')? 'selected="selected"': ''?>>Pembatu kasir</option>
						<option value="lai" <?php echo ($request['posisi']=='lai')? 'selected="selected"': ''?>>Lainnya</option>
					</select>
				</div>
				<div class="form-group">
					<label>Tanggal Masuk</label>
					<div id="dp3" class="input-append date" data-date-format="yyyy-mm-dd">
					<input name="tgl_masuk" class="span2" type="text" readonly="" value="<?php echo (isset($request['tgl_masuk']))? $request['tgl_masuk']:date('Y-m-d') ?>" size="16">
					<span class="add-on">
					<i class="fa fa-calendar"></i>
					</span>
					</div>
				</div>
				<div class="form-group">
					<label>Status</label>
					<select class="form-control chosen-dropdown" name="status">
						<option value="1" <?php echo ($request['status']==1)? 'selected="selected"': ''?>>Aktif</option>
						<option value="0" <?php echo ($request['status']==0)? 'selected="selected"': ''?>>Tidak aktif</option>
					</select>
				</div>
				<div class="form-group">
					<label>Alamat</label>
					<textarea rows="3" name="alamat" class="form-control"><?php echo (isset($request['alamat']))? $request['alamat']:'' ?></textarea>
				</div>
				<div class="form-group">
					<label>Gaji pokok</label>
					<input class="form-control" name="gaji_pokok" value="<?php echo (isset($request['gaji_pokok']))? $request['gaji_pokok']:'' ?>">
				</div>
				
				<button class="btn btn-primary" type="submit">Update</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>