
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>Nama lengkap</th>
                                            <th>Alamat</th>
											<th>Posisi</th>
											<th>Gaji</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($pegawai as $user):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $user['nama']?></td>
                                            <td><?php echo $user['alamat']?></td>
                                            <td><?php echo $user['posisi']?></td>
											<td><?php echo $user['gaji_pokok']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('pegawai/edit/'.$user['id_pegawai'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('pegawai/delete/'.$user['id_pegawai'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('pegawai/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->