<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Edit Kriteria<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('criteria/update/'.$request['id'])?>">
				<div class="form-group">
					<label>Kriteria</label>
					<input class="form-control" name="criteria" value="<?php echo (isset($request['criteria']))? $request['criteria']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Persentase</label>
					<input class="form-control" name="persentase" value="<?php echo (isset($request['persentase']))? $request['persentase']:'' ?>">
				</div>
				<div class="form-group">
					<label>Nilai Core Fakor</label>
					<input class="form-control" name="ncf" value="<?php echo (isset($request['ncf']))? $request['ncf']:'' ?>">
				</div>
				<div class="form-group">
					<label>Nilai Secondary Faktor</label>
					<input class="form-control" name="nsf" value="<?php echo (isset($request['nsf']))? $request['nsf']:'' ?>">
				</div>
				
				<button class="btn btn-primary" type="submit">Update</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>