<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Tambah Transaksi<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form role="form" method="post" action="<?php echo site('transaksi/save')?>">
				<div class="form-group">
					<label>Resort</label>
					<select class="form-control chosen-dropdown" data-allows-new-values="true" name="jenis">
						<option value="debet">Pemasukan</option>
						<option value="kredit">Pengeluaran</option>
					</select>
				</div>
								
				<div class="form-group">
					<label>Total</label>
					<input class="form-control" name="total" value="<?php echo (isset($request['total']))? $request['total']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Keterangan</label>
					<textarea cols="70" rows="4" name="ket"><?php echo (isset($request['total']))? $request['total']:'' ?></textarea>
				</div>
				
				<button class="btn btn-primary" type="submit">Simpan</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>
