
<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>Tanggal</th>
                                            <th>Debet</th>
											<th>Kredit</th>
											<th>Total</th>
                                            <th>Pengguna</th>
											<th>Keterangan</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($trans as $_trans):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $_trans['tanggal']; ?></td>
                                            <td><?php echo ($_trans['debet']) ? '<i class="fa fa-check"></i>':'';?></td>
                                            <td><?php echo ($_trans['kredit']) ? '<i class="fa fa-check"></i>':'';?></td>	
											<td><?php echo $_trans['total'];?></td>												
                                            <td><?php echo $userModel->getNama($_trans['user_id']);?></td>				
											<td><?php echo $_trans['ket'];?></td>							
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('transaksi/addnew')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->